---
# tasks file for ssh_config
- name: Run specified tasks on current platform
  include: "{{ ansible_os_family }}.yml"
- block:
  - name: Create .ssh directory
    file:
      path: "{{ sshconfig_home }}/.ssh"
      owner: "{{ sshconfig_owner }}"
      group: "{{ sshconfig_group }}"
      state: "directory"
      recurse: yes
  - name: Check whether known_host file exists
    stat:
      path: "{{ sshconfig_home }}/.ssh/known_hosts"
    register: stat_known_hosts
    changed_when: no
  - name: Create known_hosts file
    file:
      path: "{{ sshconfig_home }}/.ssh/known_hosts"
      owner: "{{ sshconfig_owner }}"
      group: "{{ sshconfig_group }}"
      state: "touch"
    when: not stat_known_hosts.stat.exists
  - name: Check whether hostname exists in known_hosts file
    command: "ssh-keygen -F {{ item }} -f {{ sshconfig_home }}/.ssh/known_hosts"
    register: results_hostname_exists
    with_items: "{{ sshconfig_knownhosts }}"
    ignore_errors: yes
    changed_when: no
  - name: Add hostname as known hosts to known_hosts file
    shell: "ssh-keyscan {{ item.item }} >> {{ sshconfig_home }}/.ssh/known_hosts"
    with_items: "{{ results_hostname_exists.results }}"
    when: "item.rc != 0"
  - name: Copy public keys under .ssh directory
    copy:
      dest: "{{ sshconfig_home }}/.ssh/{{ item | basename }}"
      content: "{{ lookup('file', item) }}"
      owner: "{{ sshconfig_owner }}"
      group: "{{ sshconfig_group }}"
      mode: 0644
    with_items: "{{ sshconfig_publickey_paths }}"
  - name: Copy private keys under .ssh directory
    copy:
      dest: "{{ sshconfig_home }}/.ssh/{{ item | basename }}"
      content: "{{ lookup('file', item) }}"
      owner: "{{ sshconfig_owner }}"
      group: "{{ sshconfig_group }}"
      mode: 0600
    with_items: "{{ sshconfig_privatekey_paths }}"
  - name: Add authorized public keys
    authorized_key:
      user: "{{ sshconfig_owner }}"
      key: "{{ lookup('file', item) }}"
      path: "{{ sshconfig_home }}/.ssh/authorized_keys"
      manage_dir: no
    with_items: "{{ sshconfig_authorizedkey_paths }}"
  - name: Copy SSH client config under .ssh directory
    blockinfile:
      dest: "{{ sshconfig_home }}/.ssh/config"
      content: "{{ lookup('file', sshconfig_clientconfig_path) }}"
      owner: "{{ sshconfig_owner }}"
      group: "{{ sshconfig_group }}"
      mode: 0600
      create: yes
    when: "sshconfig_clientconfig_path is defined"
  become: yes
